import localFont from "next/font/local";
import "./globals.css";
import AppHeader from "./sections/Appheader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AppHeader />
        <div className="mx-auto mt-6 w-full px-0 lg:my-6 lg:px-0 ">
          <div className="mx-auto lg:max-w-screen-xl w-full">
            <div className="w-full px-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
